id: I0FFB36FA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T04:44:43+00:00'
last_modified: '2022-06-08T08:43:47.683617+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC456
  title: 'སློབ་འབྲིང་སློབ་མའི་ལྷུག་རྩོམ་ལེགས་བཏུས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F018:
      image_group_id: I2PD18768
      title: ''
      total_pages: 138
      order: 1
      base_file: F018.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
